### ISSUE TITLE
当key不可用了，支持自动disable+自动轮转

### ISSUE THREAD

**Issue by Zuckonit** [lzhpo/chatgpt-spring-boot-starter#4]
apikey可能被限流或者钱用完了等异常情况下，自动踢出这个key。
或者留一个口子，当出现这类异常的时候，有listener可以操作

**Comment by lzhpo** [comment]
最近比较忙，没注意看，已实现！
参考文档：
- 失效 API Key 自动轮转：https://github.com/lzhpo/chatgpt-spring-boot-starter#%E6%A6%82%E8%A7%88
- 关于异常处理：https://github.com/lzhpo/chatgpt-spring-boot-starter#6-%E5%85%B3%E4%BA%8E%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86
