### ISSUE TITLE
找不到依赖项

### ISSUE THREAD

**Issue by StarCode000** [lzhpo/chatgpt-spring-boot-starter#5]
刚刚开了个项目，可是没法找到你的这个starter，这是为啥
![Snipaste_2023-06-13_14-51-22](https://github.com/lzhpo/chatgpt-spring-boot-starter/assets/59649631/e9da2248-dd22-4ec5-8017-374eb2a996da)

**Comment by lzhpo** [comment]
我在阿里云仓库检查了依赖是存在的
![image](https://github.com/lzhpo/chatgpt-spring-boot-starter/assets/42663571/44a46da4-b9cb-483d-ab72-61389bb0c620)

因为你用的是老版本的阿里云仓库地址，如果存在这种拉不到依赖的问题，可以换成新版本的地址：https://maven.aliyun.com/repository/public

参考文档：https://developer.aliyun.com/mvn/guide
